baseURL = "https://blog.rysh.tech/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "rysh's blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true


[params]
title = "rysh's blog"
author = "Ishibashi Ryuhei"
description = "Expert at Refactoring"
profilePicture = "images/profile.pngf"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]
googleAnalytics = "G-81V1G7GCTH"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/cactaceae"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://jp.linkedin.com/in/ryuhei-ishibashi-44291570"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/rysh"


## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

#  [[menu.main]]
#  name = "About"
#  weight = 300
#  identifier = "about"
#  url = "/about/"